//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQToAQL.Tests.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LINQToAQL.Tests.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Id&quot;:6,
        ///      &quot;AuthorId&quot;:2,
        ///      &quot;InResponseTo&quot;:1,
        ///      &quot;SenderLocation&quot;:{
        ///         &quot;X&quot;:31.5,
        ///         &quot;Y&quot;:75.56
        ///      },
        ///      &quot;Message&quot;:&quot; like t-mobile its platform is mind-blowing&quot;
        ///   },
        ///   {
        ///      &quot;Id&quot;:11,
        ///      &quot;AuthorId&quot;:1,
        ///      &quot;InResponseTo&quot;:1,
        ///      &quot;SenderLocation&quot;:{
        ///         &quot;X&quot;:38.97,
        ///         &quot;Y&quot;:77.49
        ///      },
        ///      &quot;Message&quot;:&quot; can&apos;t stand at&amp;t its plan is terrible&quot;
        ///   },
        ///   {
        ///      &quot;Id&quot;:12,
        ///      &quot;AuthorId&quot;:10,
        ///      &quot;InResponseTo&quot;:6,
        ///      &quot;SenderLoca [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FacebookMessages {
            get {
                return ResourceManager.GetString("FacebookMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;id&quot;:1,
        ///      &quot;alias&quot;:&quot;Margarita&quot;,
        ///      &quot;name&quot;:&quot;MargaritaStoddard&quot;,
        ///      &quot;UserSince&quot;:&quot;2012-08-20T10:10:00.000Z&quot;,
        ///      &quot;FriendIds&quot;:[
        ///         2,
        ///         3,
        ///         6,
        ///         10
        ///      ]
        ///   },
        ///   {
        ///      &quot;id&quot;:2,
        ///      &quot;alias&quot;:&quot;Isbel&quot;,
        ///      &quot;name&quot;:&quot;IsbelDull&quot;,
        ///      &quot;UserSince&quot;:&quot;2011-01-22T10:10:00.000Z&quot;,
        ///      &quot;FriendIds&quot;:[
        ///         1,
        ///         4
        ///      ]
        ///   },
        ///   {
        ///      &quot;id&quot;:3,
        ///      &quot;alias&quot;:&quot;Emory&quot;,
        ///      &quot;name&quot;:&quot;EmoryUnk&quot;,
        ///      &quot;UserSince&quot;:&quot;2012-07-10T10:10:0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FacebookUsers {
            get {
                return ResourceManager.GetString("FacebookUsers", resourceCulture);
            }
        }
    }
}
